### ISSUE TITLE
Support λ in lang mode

### ISSUE THREAD

**Issue by wetpussy** [willghatch/racket-rash#10] opened 2018-04-14 12:41 UTC
Unfortunately λ symbol instead of `lambda` doesn't work
```
> ((λ () #t))
((λ () #t))
#(struct:exn:fail:read readline-input:10:3: unexpected closing delimiter »
 #<continuation-mark-set> (#(struct:srcloc readline-input 10 3 143 #f)))
Result 16:
#(struct:exn:fail:contract:variable %%linea-racket-line: undefined;
 cannot reference an identifier before its definition
  in module: "/home/urara/.racket/6.12/pkgs/rash/rash/private/repl-namespace.rkt" #<continuation-mark-set> %%linea-racket-line)
17:34 /home/urara/
Result 17:
#(struct:exn:fail:syntax readline-input:10:5: #%app: missing procedure expression;
 probably originally (), which is an illegal empty application
  in: (#%app) #<continuation-mark-set> (#<syntax:10:5 (#%app)>))
17:34 /home/urara/
#(struct:exn:fail:read readline-input:10:10: unexpected closing delimiter )
 #<continuation-mark-set> (#(struct:srcloc readline-input 10 10 150 #f)))
Result 18:
#(struct:exn:fail:contract:variable %%linea-racket-line: undefined;
 cannot reference an identifier before its definition
  in module: "/home/urara/.racket/6.12/pkgs/rash/rash/private/repl-namespace.rkt" #<continuation-mark-set> %%linea-racket-line)
17:34 /home/urara/
#(struct:exn:fail:read readline-input:10:11: unexpected closing delimiter )
 #<continuation-mark-set> (#(struct:srcloc readline-input 10 11 151 #f)))
Result 19:
#(struct:exn:fail:contract:variable %%linea-racket-line: undefined;
 cannot reference an identifier before its definition
  in module: "/home/urara/.racket/6.12/pkgs/rash/rash/private/repl-namespace.rkt" #<continuation-mark-set> %%linea-racket-line)
17:34 /home/urara/
> ((lambda () #t))
((lambda () #t))
Result 20:
#t
17:35 /home/urara/
> 
```

**Comment by willghatch** [comment] 2018-04-14 15:08
Hi.

It looks like the issue is with the readline package which is turning `λ` into `Î»`.  This is fixed by installing the `readline-gpl` package, which uses libreadline instead of libeditline (or something like that -- I don't recall exactly the name of the non-gpl knockoff library that they are using).  I've been meaning to put that in the documentation for some time, but haven't gotten around to it.

Thanks for the report, and sorry about the confusion.

Also, out of curiosity, how are you typing `λ` in the repl?  (I use a custom keyboard layout that includes λ since I use it so much, and I created a package called the-unicoder to input arbitrary unicode into any window, but I'm curious about how others approach it too.)

**Comment by wetpussy** [comment] 2018-04-14 16:04
Yes, it does.

**Closed** 2018-04-14 16:04 UTC
